### ISSUE TITLE
useDeliveryGroup returning empty result

### ISSUE THREAD

**Issue by adearriba-fik** [Shopify/ui-extensions#1173]
## List the package(s) involved in the issue
@shopify/checkout-ui-extensions-react Version: 0.27.1"

## Describe the bug
useDeliveryGroups hook returns empty array even when there are Shipping Methods. This is not something I can reproduce constantly. Normally I need to open the store in a private tab and go to the checkout. Sometimes it happens, sometimes it doesnt. 

If I refresh, it works. Seems like there is a dependency missing in the hook so it's not refreshing correctly the value.

Here is a picture of the error where I'm printing the useDeliveryGroups value in a useEffect:

````js
const deliveryGroups = useDeliveryGroups();
useEffect(() => {
    console.log("deliveryGroups changed", deliveryGroups);
}, deliveryGroups);
````

![image](https://github.com/Shopify/ui-extensions/assets/135005356/3a96d74d-9de7-4d64-b2da-c33cb52b4881)

## Steps to reproduce the behavior:

1. Open store in your browser's private window/tab
2. Go to checkout, fill out information page information
3. Continue to Shipping methods

## Expected behavior
useDeliveryGroups has the Shipping Methods details.

<img width="794" alt="image" src="https://github.com/Shopify/ui-extensions/assets/135005356/23504c74-0c0b-40d7-b144-0b7088885206">

## Additional context
We are using a Shipping Method selector app named: [Calcurates](https://apps.shopify.com/calcurates?locale=es)

**Comment by rbarreca** [comment]
Seeing some posts regarding Functions showing empty deliveryGroups unexpectedly as well. Same root cause?
- https://community.shopify.com/c/shopify-functions/product-discount-functions-api-no-deliverygroups-returned/td-p/2184736
- https://community.shopify.com/c/shopify-functions/shopify-functions-bug-delivery-groups-array-is-empty/td-p/2000018

**Comment by mleandres** [comment]
Additionally, we've been getting more and more reports of this from larger merchants so I think it's safe to bump this to SEV-3

**Comment by FeliciaChenz** [comment]
Hey team! This issue is happening on C1 and it's reported by one of our Enterprise merchants. Could we please get some assistance with this? I documented this in [the Merchant Bug Tracker](https://merchant-bug-tracker.shopifycloud.com/bugs/4229) after this discussion here [this new thread in #help-checkout-extensibility](https://shopify.slack.com/archives/C01FT69928K/p1715700033200009) 
@mleandres  @NabeelAhsen
