### ISSUE TITLE
Disabiling autofill on TextField don't work (typo?)

### ISSUE THREAD

**Issue by patryk-smc** [Shopify/ui-extensions#1476]
`@shopify/ui-extensions-react 2023.10.0`

`<TextField>` component `autocomplete` prop:

Types say:
>When set to false, you are indicating that this field contains sensitive information, or contents that are never saved, like one-time codes.

But when we do that, the HTML input in the checkout has an attribute `autocomplete="none"` which is non-standard and it doesn't work as I get autocomplete suggestions in Chrome. [According to the spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-expectation-mantle:~:text=expectation%20mantle...-,The%20%22off%22%20keyword,-indicates%20either%20that), it should be `autocomplete="off"`

**Comment by simontaisne** [comment]
Hi @patryk-smc, I'm looking at this issue, and things are not exactly as straightforward as expected in the specs. Google chrome does not always respect `autocomplete="off"`, and one way to prevent autofill is to use an unknown value. You can read more about the issue here https://issues.chromium.org/issues/40093420.

> It doesn't work as I get autocomplete suggestions in Chrome

Could you please clarify whether these suggestions are originating from Chrome itself or from extensions such as password managers?

**Comment by simontaisne** [comment]
Yes, this workaround could impact how password managers and other extensions function since they also rely on `autocomplete='off'`.  I'm going to dig a little deeper into this and keep you posted.

**Comment by simontaisne** [comment]
Hey @patryk-smc! We've just released a fix for this. Thanks again for the report!
