### ISSUE TITLE
useCustomer hook throws in customer-account.profile.block.render target

### ISSUE THREAD

**Issue by andrewpye** [Shopify/ui-extensions#1914]
## Please list the package(s) involved in the issue, and include the version you are using
`@shopify/ui-extensions`: 2024.1.1
`@shopify/ui-extensions-react`: 2024.1.1

## Describe the bug
Calling the `useCustomer()` hook exported from `@shopify/ui-extensions-react/customer-account` results in an error being thrown:

```
ScopeNotGrantedError: Using buyer identity requires having personal customer data permissions granted to your app
```

My development app that I'm encountering this with is a custom app, which according to Shopify docs should have access to restricted data:

![image](https://github.com/Shopify/ui-extensions/assets/5737342/18a860ae-9106-4c0b-bf8d-43d3f9974060)

A colleague with a public app with protected data access granted (name + email but _not_ phone + addresses) also gets the same error when using the hook in the same extension target. We've been using the `useCustomer()` hook on other UI extensions (checkout, order status page, thank-you page) without issue for months so I assume that something is either broken or works differently on the profile target compared to other extension targets.

## Steps to reproduce the behavior:

1. Create a React customer profile extension targeting `customer-account.profile.block.render` ;
1. Import and call the `useCustomer()` hook in that extension;
1. Run the extension via `yarn dev`, preview it, and observe the error in the console.

## Expected behavior
`useCustomer()` does _not_ error and returns the customer data.

## Screenshots
N/A

## Additional context
N/A

**Comment by gracerivas** [comment]
Hey @andrewpye, thank you for reaching out to us, I am Grace I'm from the customer accounts team. 

The profile extension only can access the standard API and within the standard API you can make use of the `authenticatedAccount` just as specified in this documentation below: 
 
* https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/targets/profile-(default)/customer-account-profile-block-render
* https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/apis/authenticated-account

The hook wouldn't work for this specific extension because it needs the `buyerIdentity` which is only accessible in order status pages. 

* https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/targets/order-status/customer-account-order-status-block-render. 

Let us know if you have any other question.

**Comment by andrewpye** [comment]
Thanks @gracerivas! We'll have a look at that when we have the opportunity and I'll respond here once we've done so 🙇

In the meantime I'd like to share some feedback around this though if that's OK. The differing API between different extension points – both the broader surface differences (e.g. checkout vs. customer account), and the variation between extension points within the _same_ surface (e.g. order status page vs. account profile page) – means that developers have to constantly refer to documentation to figure out how to implement things that were easy and intuitive in one extension in another. For example in this case, a hook called `useCustomer()` seems like a nice, intuitive way of accessing the currently authenticated customer, and works great on the order status page – but if we want the same data in the account profile page, we have to use a _different_ (and IMO less clearly named) hook like `useAuthenticatedAccountCustomer()` (from what I understood from the docs you linked above, anyway). I'm not sure why `useCustomer()` hasn't been updated to "Just Work" on the account profile page instead of introducing a whole new hook for the same purpose 😕 As a result, the developer experience is inconsistent and frustrating.

This inconsistency also makes it much harder than it should be to share code cleanly between extensions. We have multiple extensions across various points, and many of them need to access the customer data so that we can identify the customer in our own back end and provide them with the correct experience. When we were just working with checkout UI extensions (before the introduction of customer account UI extensions) and could just use `useCustomer()` everywhere, we built easily-reusable utilities for performing this kind of step. With the differences in API between extension points highlighted above, these reusable utilities have become useless and we're going to either have to spend large amounts of time refactoring all of our existing extensions to be able to continue sharing utilities between them, or otherwise duplicating utilities that still work fine in checkout UI extensions and editing them to be usable on customer account UI extensions. I'm sure you can understand that neither of these "solutions" is ideal; it would have been nice if there had been some consideration given to such situations before making the APIs between extension points so inconsistent. I hope that this will be resolved at some point in the future, but in the meantime it seems like we're stuck having to build sub-optimal code in order to work around these difficulties.

Thanks for your understanding!

**Comment by gracerivas** [comment]
Hey @andrewpye, thank you for your feedback. Definitely extensions are on the making at the moment, its hard to make a unified data retrieval across all extensions as its not as straight forward across many types of customers, types of authentication and types of extensions. In checkout, everything is linked to one order but in customer accounts there can be different experiences from B2B and D2C customers and we have three types of authentications. So the data retrieval from checkout is not aligned with how we should retrieve data from our pages. We utilize ` useAuthenticatedAccountCustomer()` because we want to make the developer know that this customer is authenticated mode. 

Moreover, sustaining one single form of access to the customer, means that for one of our teams to make one modification we would have to consistently ask for permission across all the teams that make use of customer, which this would lead to a huge delays and perhaps not everybody would be happy with what to show from customer in which extensions. We are just trying to produce the best outcome for each area of concern. 

Nevertheless, I will point this out to our team and see what their thoughts are.  In the meantime, feel free to always come back to us with further questions.

**Comment by andrewpye** [comment]
Thanks for the insight @gracerivas 😁 There are probably a lot of deeper details about the different surfaces that I haven't come across so far, so maybe I'm expecting/hoping for something too simplistic 😜 

I was able to verify that after updating our `@shopify/ui-extensions` and `@shopify/ui-extensions-react` dependencies to `unstable`, I could use `useAuthenticatedAccountCustomer()` in our profile page extension and successfully retrieve the customer's ID. Since that provides us with the information we need, I'll close this issue. Thanks again for your help!
