### ISSUE TITLE
Admin action Authorize button throws error instead of redirecting to auth flow

### ISSUE THREAD

**Issue by mikek-ok** [Shopify/ui-extensions#2183]
## Please list the package(s) involved in the issue, and include the version you are using

ui-extensions V2024.4.1
ui-extensions-react V2024.4.1

## Describe the bug

When attempting to access an admin action while there is no user session or a session is expired, the admin UI displays an error message that reads "This application's data access requirements have changed, you need to re-authorize it.", but when the `Authorize` button is clicked, it throws up an error instead of authorizing the user.

## Steps to reproduce the behavior:

1. Expire a session, or don't have a session.
1. Try to access any action on our app.
1. Get the above dialog and try to click `Authorize`.

## Expected behavior

Clicking `Authorize` should redirect the user into our usual auth flow and correctly auth the user.

## Screenshots

Dialog:
![image](https://github.com/Shopify/ui-extensions/assets/175275523/b7f769c8-0b02-44dc-a60e-4142dcfdc30b)

When clicking `Authorize`:
![image](https://github.com/Shopify/ui-extensions/assets/175275523/d5af3a10-648a-4a4d-aba9-299fcd55423c)

## Additional context

What happens is that our remix app (built on top of the shopify remix app template) returns a 401 as expected, which causes the above dialog to show, but when `Authorize` is clicked what we'd expect to happen is that the user gets redirected into our auth flow. Instead, there is a `AppAccessRequestGrantMutation` graphql request which fails with "The app does not have scopes declared on Shopify.". Our app handles scopes itself, so it should be redirecting the user into our remix instance for auth.

Once the dialog is shown, we don't see any further requests to our app or any other attempts to enter our usual auth flow.

**Comment by owlyowl** [comment]
As discussed with @henrytao-me at editions.dev

**Comment by owlyowl** [comment]
Hi Henry!
We currently store the offline token.

We were calling the auth as depicted in Shopify's examples on how to call
APIs from an embedded remix app route.

I can't see anywhere that this has changed in Shopify's docs.

Is this not the case?

**Comment by owlyowl** [comment]
We're trying to be a good first class citizen and dynamically introduce scopes as they are required.

We couldn't used the fixed scopes in the core file as we dynamically adjust scopes per app subscriber so in our session handling we provide dynamic scopes on the fly.

I'd love to arrange a catch up call with the team to explain.

**Comment by MitchLillie** [comment]
Hi @owlyowl - we are still looking into this. I think we have a fix for you. We should have an update soon!

**Comment by MitchLillie** [comment]
Hi @owlyowl!

I think this should be fixed — please let us know if you are still seeing the issue on your end.

We appreciate the sentiment of wanting to be a first class citizen. To that end, [Shopify managed install](https://shopify.dev/docs/apps/build/authentication-authorization/app-installation) is the [recommended](https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/authorization-code-grant) way to manage scopes as an app. Furthermore, [offline tokens](https://shopify.dev/docs/apps/build/authentication-authorization/access-tokens/offline-access-tokens), like what Okendo uses, are meant for long-term access to a store where user interaction is not involved, which is not the case with how you’re currently them. 

If you want to apply different permissions per-user, we recommend that your app have a stable set of permissions it requests. Per-user permissions can then be enforced before completing requests from your backend.

Recommendations:

* Use [Shopify managed install](https://shopify.dev/docs/apps/build/authentication-authorization/app-installation). 
* If Shopify managed install is not possible, update code on your end to request one offline token per shop, rather than per user as is currently happening. Then, you can ensure all queries go through your backend, where you can apply specific user permissions, as needed.

Happy to meet to chat further! Feel free to reach out at [mitch.lillie@shopify.com](mailto:mitch.lillie@shopify.com) if you’d like to set up some time.

**Comment by owlyowl** [comment]
Thanks Mitch and Henry!
We'll take a look this morning.

We really appreciate you looking into this.
