### ISSUE TITLE
Extended shipping method types

### ISSUE THREAD

**Issue by GYMarshy** [Shopify/ui-extensions#504]
## Please list the related package(s)

checkout-ui-extensions

## If this related to specific APIs or components, please list them here

Related to: https://shopify.dev/api/checkout-extensions/checkout/extension-points/api#react-hooks

## Is your feature request related to a problem? Please describe.

A native way to offer enhanced shipping methods that require the user to specify a delivery date or collection point

## Describe the changes you are looking for

Further to the discussion here: https://github.com/Shopify/ui-extensions/issues/406

We currently have to customise the checkout.liquid and add write a lot of JS to offer the following types of shipping methods:

- Named day (via a datepicker)
- Collection point (via a map / list of points)

Both of these types of shipping methods have become fairly commonplace, and are essential if our merchants are to offer shipping options that rival Amazon, or brands on other ecomm platforms etc.

It's not enough to just offer a datepicker or map UI element though. The list of available dates or locations can vary depending on the cart contents. What we would love is to see some kind of tie-up between these front end elements and the Carrier Service functionality. The flow would work as follows:

- Customer enters address (as now)
- Carrier service is called (as now)
- Carrier service returns list of methods (as now)
- Some of these methods may return a list of dates or locations (as well as title & price)
- User selects a method, and the appropriate UI appears to gather the extra data
- Extra data is attached to the order as a metafield

## Describe alternatives you’ve considered

Currently implemented via customisations to checkout.liquid with AJAX to enrich the UI

## Additional context

Example datepicker implementation from www.mamasandpapas.com via customised checkout.liquid

<img width="670" alt="image" src="https://user-images.githubusercontent.com/986597/191591417-80b96bcc-a67f-4142-a3ef-f2b892badc91.png">

**Comment by gerwinbrunner** [comment]
+1

**Comment by jarthorn** [comment]
These features are definitely on our radar and we are exploring this now. We are exploring not only elements like DatePicker and map components, but also the end-end of how to ties these together. Thank you for this detailed summary of what you are looking for here!

**Comment by GYMarshy** [comment]
@jarthorn - is it likely that as part of this we will be able to use a 3rd party service for delivery calculations? Our current implementation fires off a request to a shipping broker service to get a list of valid methods.

**Comment by jarthorn** [comment]
Are you referring to using the Shopify [carrier service API](https://shopify.dev/docs/api/admin-rest/2023-01/resources/carrierservice), or is this is bespoke integration with a 3rd party service? I expect for "ship to buyer" delivery we will continue to use the carrier service. We are considering different APIs for shipping to pickup points and pickup in store to offer more flexibility in those scenarios. If you have particular scenarios where existing APIs aren't flexible enough I'd love to hear details because we're working on this right now.

**Comment by jarthorn** [comment]
Thank you so much for these details! We've observed this pattern on many stores and it's understandable. Clearly you're being forced to resort to hacks here because of the lack of flexibility in the underlying system. What we are aiming for is that the "Delivery Method" chosen by the buyer accurately reflects which of the three fundamental choices available ("We'll ship it to you", "You come to pick it up", "We ship it to a place where you will pick it up"). Then, we want to enable additional levels of flexibility for **each** delivery method, through a combination of UI extensions and backend integrations with Shopify Functions or things like the carrier API, to enable all the various business needs that individual merchants have. In other words we are working on building a solution that can anwer "Yes" to all your three questions here.

**Comment by GYMarshy** [comment]
Sounds perfect @jarthorn. We've got lots of experience with these sorts of retailers so happy help whenever.

**Comment by colinbrogan** [comment]
+1
One of my shopify plus clients is also using a checkout.liquid solution which I developed for him, and which we will lose in August 2024. My implementation looks like this:
We first changed the "Ship to home" option on the first shipping step to say "Ship to home or Nearby Warehouse", to avoid confusions for the customer which @jarthorn mentions: 
![nearby_warehouse](https://github.com/Shopify/ui-extensions/assets/1031473/c6f4967c-a898-44ac-aae3-33a391412a4b)

We then show various options of warehouses nearby which they can drive to, embedding a google maps instance to show the relative drive-times from their house. Each time a new option is selected, the map is redrawn, and explanatory text is changed:
![chicago](https://github.com/Shopify/ui-extensions/assets/1031473/f0410319-d5b5-431f-84c8-a0f30b1b07dd)

This was all-done through CSS and javascript embeds on checkout.liquid, which added complexity to maintenance at each checkout.liquid upgrade. Nonetheless, we've managed this, because the feature drives significant revenue for my client. As I understand Checkout UI now, we have no option to reimplement this feature even in the most simplified and paired-down form. We can compromise on where these embeds are placed and what kind of content is allowed, but as I understand it now, there isn't any hook I can subscribe to on shipping method changes, to exchange any content anywhere on the checkout page. Just a simple shipping option change hook would allow us to do a basic implementation.

If shopify can inform us on whether or not the API's proposed on this thread, or API's like them, will be added to extensions UI, I would greatly appreciate it.

**Comment by Job-madi** [comment]
+1

**Comment by kgolts** [comment]
Any progress on this in Checkout UI?  
We are trying to recreate this functionality for this store: https://giftbasketstore.com/
![Shipping_-_The_Gift_Basket_Store_-_Checkout](https://github.com/Shopify/ui-extensions/assets/6774610/77f20250-6aa7-459d-ae02-561cc199d3ad)
