### ISSUE TITLE
`useBuyerJourneyIntercept` blocks next step when `behavior` is set to `allow`

### ISSUE THREAD

**Issue by Jay-Plumb** [Shopify/ui-extensions#560]
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/checkout-ui-extensions-react": "^0.20.0",

## Describe the bug

The code example within https://shopify.dev/apps/checkout/validation/validate-fields for .jsx throws the following console error:

```
ƒ (){if(a)throw new Error("You attempted to call a function that was already released.");if(!s.has(r))throw new Error("You attempted to call a function that was already revoked.");for(var n=arguments.l…
```

Specifically, the user is unable to click `continue to shipping` even when a valid age input is supplied.

This is specifically related to the function `useBuyerJourneyIntercept` (lines 29 to 81) in the official code example

## Steps to reproduce the behavior:

1. Go through  https://shopify.dev/apps/checkout/validation/validate-fields tutorial

## Expected behavior
1. No console error when useBuyerJourneyIntercept is in use
2. When the age input field is valid, the user should be able to click `continue to shipping`

**Comment by chienit3bk** [comment]
same, if this `Validations extension`  is placed at `Shipping page` or `Payment page`, you won't go to `Shipping page` at store front by press button `Continue to Shipping` at `Information page`

**Comment by jamesvidler** [comment]
Thank you @Jay-Plumb and @chienit3bk for reporting this issue. Can you confirm whether you were using React or the Vanilla JS example, whether this is in a local or installed extension, and which exact extension point you were targeting?

**Comment by chienit3bk** [comment]
i try putting this extension `https://shopify.dev/apps/checkout/validation/validate-fields`  by using React, and i use `Checkout::Dynamic::Render[Delivery1]` and it block my checkout from Information page

**Comment by jamesvidler** [comment]
Hi @chienit3bk thank you for sharing that video, it was very helpful to reproduce the issue. I can confirm I am seeing the same issue with an installed extension (rather than rending a local extension which does not seem to have this issue).

**Comment by jamesvidler** [comment]
@Jay-Plumb it looks like this issue is a little different than what @chienit3bk and I are looking at now. I just wanted to confirm with you that you had an issue with a local extension running on the Information step, is that correct? We may be looking at two separate issues here.

**Steps to reproduce inability to progress past Information step**:
1. Deploy an extension that requires user input to be able to progress through the buyer journey (i.e. the [validation tutorial](https://shopify.dev/apps/checkout/validation/validate-fields)) 
2. Activate the persisted extension in either the **Shipping** or **Payment** step of a multi-step checkout in the checkout editor.
3. Launch a checkout on the shop and note that you cannot continue past the **Information** step. The extension is expecting input, but the buyer is unable to set input because they haven't seen the extension yet.
4.

**Comment by jamesvidler** [comment]
Update here. We've shipped a patch which now prevents the buyerJourney from being blocked when it is not rendered in the current step. Please let us know if you continue to run into this issue.
