### ISSUE TITLE
useCustomer is always undefined for b2b customers

### ISSUE THREAD

**Issue by themazim** [Shopify/ui-extensions#763]
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/checkout-ui-extensions 0.24.0

## Describe the bug

`useCustomer()` returns undefined if the logged in customer is a b2b / new account user.

## Steps to reproduce the behavior:

Use the B2B Feature, add a company and add a customer to the company. Make sure to use the new account login.

Login, put something in the basket and proceed to checkout. Add your extension for i.e. discount and use this in your code

```
const customer = useCustomer();
console.log('customer', customer);
```

You will see customer: undefined in the console.

## Expected behavior

Customers who use the new login should be available through useCustomer() and actually return the customer object.

**Comment by sjanczy2** [comment]
Hi @themazim, this is expected behavior at the moment as checkout UI extensions don't support reading B2B customer objects. We need to add support for [purchasing company](https://shopify.dev/docs/api/storefront/unstable/objects/PurchasingCompany) and the underlying objects. This is a planned enhancement.

**Comment by tibo-shop** [comment]
We will fix this issue as part of adding [B2B context in Checkout UI Extensions](https://vault.shopify.io/gsd/projects/35011)
