### ISSUE TITLE
[Branding API] Explore adding a "reset to default" mutation for checkout profiles

### ISSUE THREAD

**Issue by gil--** [Shopify/ui-extensions#777]
## Please list the package(s) involved in the issue, and include the version you are using

[checkoutBrandingUpsert](https://shopify.dev/docs/api/admin-graphql/unstable/mutations/checkoutBrandingUpsert)

## Describe the bug

On every store type I've tested (Development, Shopify Plus sandbox, Shopify Plus), the upsert mutation results in the same exact error:

```
[ { field: null, message: 'branding_settings_not_enabled' } ]
```

## Steps to reproduce the behavior:

1. Change Admin API to "unstable"
2. Run a valid upsert query such as:

```gql
mutation checkoutBrandingUpsert($checkoutBrandingInput: CheckoutBrandingInput!, $checkoutProfileId: ID!) {
  checkoutBrandingUpsert(checkoutBrandingInput: $checkoutBrandingInput, checkoutProfileId: $checkoutProfileId) {
    userErrors {
      field
      message
    }
  }
}
```

variables:
```json
{
  "checkoutProfileId": "gid://shopify/CheckoutProfile/123",
  "checkoutBrandingInput": {
    "designSystem": null
  }
}
```

## Expected behavior

A successful update of the checkout branding

## Screenshots
![CleanShot 2023-03-05 at 15 28 30](https://user-images.githubusercontent.com/3484527/222984196-3ecde91e-b8a7-4330-9640-291dee1e1522.png)

**Comment by cdarland** [comment]
This feedback is super helpful, @gil-- ! Thx for the quick reply and your example. 

This discussion has actually come up a couple times internally, but we were uncertain what the appetite would be from third-party dev partners. Based on your feedback and experience I'll get this in the backlog. TBD on when we can prioritize it as of right now, but I'll keep everyone posted when we know more.

**Comment by olivierlabreche** [comment]
We did some more investigation on this topic.
Writing "null" is not enabled at `designSystem` or `customizations` level because they are not keys [accessible to external users](https://github.com/Shopify/shopify/blob/main/components/checkouts/core/app/services/checkouts/branding/checkout_branding_access_checker.rb). 
For staff stores where there is no such key access limitation, writing `designSystem` to "null" does not propagate to the sub-fields, though writing "customizations" works.
We will look into fixing this. We could either allow writing to the top-level fields or potentially add a new flag or mutation to reset all settings.

**Comment by gil--** [comment]
@jun-shop @olivierlabreche I'm a bit delayed but just fyi, the new branding reset via null works perfectly. Thank you!
